name: ukofePonyPack
main: com.github.chaomaster.ukofePonyPack.ukofePonyPack
version: 0.4.0
description: Provides various pony powers based on the player's skin.
author: chao-master.github
commands:
  ponyinfo:
    aliases: info
    usage: 'Usage: /<command> {player}'
    permission: ukofePonyPack.info
  ponyrecheck:
    aliases: recheck
    usage: 'Usage: /<command> {player}'
    permission: ukofePonyPack.recheck
  ponyassign:
    aliases: assign
    usage: 'Usage: /<command> {player} [type] {duration}'
    permission: ukofePonyPack.assign
  ponyreload:
    permission: ukofePonyPack.reload