name: ukofePonyPack
main: com.github.chaomaster.ukofePonyPack.ukofePonyPack
version: 0.4.0
description: Provides various pony powers based on the player's skin.
author: chao-master.github
commands:
  info:
    usage: 'Usage: /<command> {player}'
  recheck:
    usage: 'Usage: /<command> {player}'
  assign:
    usage: 'Usage: /<command> {player} [type] {duration}'