disabled: false
ponyTypes: [Earth]

damageMultiplier: 1.1
resistanceDivisor: 1.1
foodbarMinium: 5
foodbarPreserveChance: 0.1
wheatBonus: 1
netherWartBonus: 2
cocoaBonus: 2
potatoBonus: 2
carrotBonus: 2
